version: '3.8'

services:
  maarch_db:
    image: postgres:14
    container_name: maarch_db
    restart: always
    environment:
      POSTGRES_USER: maarch
      POSTGRES_PASSWORD: maarch
      POSTGRES_DB: maarchcourrier
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - maarch_net

  maarch_courrier:
    image: maarch/maarchcourrier:latest
    container_name: maarch_courrier
    depends_on:
      - maarch_db
    ports:
      - "8080:80"
    volumes:
      - courrierdata:/var/www/html
      - stockage:/opt/maarch/docservers
    networks:
      - maarch_net

networks:
  maarch_net:

volumes:
  pgdata:
  courrierdata:
  stockage:

