version: '3.8'

services:
  maarch_db:
    image: postgres:14
    container_name: maarch_db
    environment:
      POSTGRES_USER: maarch
      POSTGRES_PASSWORD: maarch
      POSTGRES_DB: maarchcourrier
    volumes:
      - maarch_pgdata:/var/lib/postgresql/data
    networks:
      - maarch_net

  maarch:
    image: maarch/maarchcourrier:latest
    container_name: maarch_courrier
    ports:
      - "8080:80"
    networks:
      - maarch_net
    depends_on:
      - maarch_db

networks:
  maarch_net:

volumes:
  maarch_pgdata:


